### ISSUE TITLE
[3h00m] Fulfilment / Partnerships

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#106]
- Customer's cliënten kunnen administreren (fulfilment)
- Sales order's sales orders
- Specifieke inlog voor customers (customer kan user zijn)

**Comment by jorr-it** [comment]
Zelfde kan ook aan de inkoopkant; zie De Uitdaging

**Comment by jorr-it** [comment]
OVERLEG 2 JULI

Eerst inkoopkant

Een customer kan een partner zijn (owning of niet)... dat is nu al zo
Een Partner kan eigenaar zijn van het geleverde maar hoeft niet (vinkje)
Orders krijgen keuzeveld Partner gelijkend Location
Customers/Supplier krijgen een keuzeveld Partner

User role "partner" introduceren
Deze user ziet alleen orders van eigen partner

Origin pickup veld moet geconverteerd naar partner
Per partner een origincode (txt)
Per partner een selectie van mogelijke locations

De partner van een product in de voorraad kan worden afgeleid van de partner van de order.
Een product heeft dus geen eigen Partner-veld itt Location-veld
Een product kan dus twee partners hebben: van PO en van SO

Verkoop gaat idem

------------------

Vervolgens krijgt Nexxus een eigen shop.
Alleen ingelogde customers/partners (en admin) zien die shop.
De shop toont het verkoopbare deel van de GEHELE voorraad
Een aankoop in deze shop wordt niet gevalideerd (geen tegoedcontrole oid)
Een aankoop in deze shop wordt aangemaakt als SO

Hiervoor moet een partner dus ook bekendstaan als customer

Bijna alle partners zijn ook customers van Nexxus.

---------------------

Importfunctie van sales orders van partner
indien nodig ook customer aanmaken
Customer uitbreiden met extern id (relatienr)
Combi partner/relatienr is de sleutel

Kolom met product info (L/C) mag in remarks
SO krijgt geen product aan zich gekoppeld
Dat doet medewerker met de scanner op basis van remarks

Aanmelden bij PostNL en uitprinten diens barcode
https://www.postnl.nl/zakelijke-oplossingen/pakket-versturen/bezorgopties/bezorgopties-aansluiten/postnl-api/

**Comment by jorr-it** [comment]
<sub>Datum: Tue 2-7-2019 10:30<br />Gewerkt: 3h00m<br />Toelichting: overleg Breedstraat<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 65554434</sub>

**Comment by jorr-it** [comment]
<sub>Datum: Tue 23-7-2019 11:00<br />Gewerkt: 4h00m<br />Toelichting: #106<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 66640693</sub>

**Comment by jorr-it** [comment]
Hi @ronalddebakker 

De eerste stappen zijn geplaatst op testlocatie copiatek.com.

Wat is te testen:
- Je kan customers aanmerken als partner
- Je kan customers en suppliers onderverdelen onder een partner
- Je kan sales en purchase orders onderverdelen onder een partner
- Een ingevulde origin bij een pickup wordt automatisch gematched aan een partner voor de bijbehorende purchase order. De origin moet grotendeels overeenkomen met de naam van de gewenste partner.

Wat is nog niet verzorgd:
- Partners kunnen inloggen
- Webshop voor partners
- Sales orders van een partner kunnen importeren
- PostNL API koppeling

Het lijkt me verstandig om eerst goed te bekijken of deze partner-oplossing de juiste oplossing is. Op copiatek.com eerst even kijken of alles nog werkt naar behoren. Zo ja, dan hoor ik het en zal ik het plaatsen op nexxus.eco, zodat je het echt kan uitproberen.

Groet,
Jorrit

**Comment by ronalddebakker** [comment]
*   Je kan customers en suppliers onderverdelen onder een partner
Ik kan een suppliers nu alleen onder brengen onder een bestaande partner, die ik aan moet maken bij customers.
Ik kan geen suppliers promoveren tot partner zoals ik dat bij customers kan doen. Zou dat niet handiger zijn om dat wel te kunnen?

  *   Je kan sales en purchase orders onderverdelen onder een partner
Ik krijg een 500 error, als ik op 2019000089<http://copiatek.com/application/salesorder/edit/89> klik en ook wanneer ik een nieuwe salesorder wil maken.


Van: Jorrit Steetskamp <notifications@github.com>
Verzonden: vrijdag 26 juli 2019 12:33
Aan: Nexxus/NSK <NSK@noreply.github.com>
CC: Ronald De Bakker <ronald.debakker@copiatek.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Nexxus/NSK] [3h00m] Fulfilment / Partnerships (#106)


Hi @ronalddebakker<https://github.com/ronalddebakker>

De eerste stappen zijn geplaatst op testlocatie copiatek.com.

Wat is te testen:

  *   Je kan customers aanmerken als partner
  *   Je kan customers en suppliers onderverdelen onder een partner
  *   Je kan sales en purchase orders onderverdelen onder een partner
  *   Een ingevulde origin bij een pickup wordt automatisch gematched aan een partner voor de bijbehorende purchase order. De origin moet grotendeels overeenkomen met de naam van de gewenste partner.

Wat is nog niet verzorgd:

  *   Partners kunnen inloggen
  *   Webshop voor partners
  *   Sales orders van een partner kunnen importeren
  *   PostNL API koppeling

Het lijkt me verstandig om eerst goed te bekijken of deze partner-oplossing de juiste oplossing is. Op copiatek.com eerst even kijken of alles nog werkt naar behoren. Zo ja, dan hoor ik het en zal ik het plaatsen op nexxus.eco, zodat je het echt kan uitproberen.

Groet,
Jorrit

**Comment by jorr-it** [comment]
De 500 error is verholpen.

Elke partner is momenteel automatisch ook een customer. Je had gezegd dat dat in de praktijk ook meestal zo is. Zodoende kunnen partners straks eenvoudig iets kopen in Nexxus. Dat een partner altijd een customer is, wil niets zeggen over de bedrijven die onder de partner vallen; dat kunnen zowel customers als suppliers zijn.

**Comment by ronalddebakker** [comment]
Dit lijkt me zo de goede kant opgaan.
Volgende week is Mark er pas weer waar ik mee overleg.

Van: Jorrit Steetskamp <notifications@github.com>
Verzonden: vrijdag 26 juli 2019 14:14
Aan: Nexxus/NSK <NSK@noreply.github.com>
CC: Ronald De Bakker <ronald.debakker@copiatek.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Nexxus/NSK] [3h00m] Fulfilment / Partnerships (#106)


De 500 error is verholpen.

Elke partner is momenteel automatisch ook een customer. Je had gezegd dat dat in de praktijk ook meestal zo is. Zodoende kunnen partners straks eenvoudig iets kopen in Nexxus. Dat een partner altijd een customer is, wil niets zeggen over de bedrijven die onder de partner vallen; dat kunnen zowel customers als suppliers zijn.

**Comment by jorr-it** [comment]
<sub>Datum: Fri 26-7-2019 08:00<br />Gewerkt: 4h00m<br />Toelichting: #106<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 66710920</sub>
