### ISSUE TITLE
Confirm after save

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#113]
Currently after succesful save of any edit screen, you go back to the index/list. I would suggest:
- two save buttons: Save and Save+Close
- a green alert at top of the next page, whatever that page is

**Comment by ronalddebakker** [comment]
this is very usefull and will enhance workflow and user expierence

**Comment by ronalddebakker** [comment]
confirm after save is already done. 
Added to this issue is the wish to have an extra button: save&close button (next to the save button)
after pressing the button, a green alert appears in the top of the page confirming the action
