### ISSUE TITLE
[3h00m] Prijskaart

### ISSUE THREAD

**Issue by nebbii** [Nexxus/NSK#15]

**Comment by jorr-it** [comment]
Nog een paar zaken te verbeteren: Lege regels eruit, prijsopbouw controleren Acer Aspire 13, TEST bovenaan, gevulde regels noemen id ipv omschrijving bij SELECT

**Comment by jorr-it** [comment]
<sub>Datum: Mon 12-11-2018 18:30<br />Gewerkt: 1h00m<br />Toelichting: verbeteringen<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 54014773</sub>
