### ISSUE TITLE
Split with new SKU's

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#150]
It would be great to have the possibility to create new SKU during individualizing. 
If I split 100 articles to individual products and I want unique sku's, I have to do this manually. This is a tedious job :) There may be a enable box to activate automatic creation of sku's

**Comment by ronalddebakker** [comment]
at the moment when using split , it always generates a new sku.
I am not sure this is desireable when splitting a bundle in 2 parts.

Can the sku option be an enable box? 
Normally you would use a new sku when individualize the  (part of a) bundle.

Individualize is used when wanting a unique property like a serial number/productkey for warranties and such.

**Comment by jorr-it** [comment]
Individualize werkt nu niet, want zelfde timestamp

**Comment by ronalddebakker** [comment]
Perfect :)
