### ISSUE TITLE
Rename Location to Store/Branch/Filiaal

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#160]

**Comment by ronalddebakker** [comment]
i actually still think location is the proper name. Per haps this can be changed individually in a translation file, as not everyone in the world will use Branch/Store/Filiaal. 
Location is a very general description.

**Comment by jorr-it** [comment]
Yes, translations are the place to be. You can give any instance its own "language" even if it is jargon. Issue closed.
