### ISSUE TITLE
Keep focus at scan field

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#165]
Scan field at index is not focussed after search
and neither after close of product

**Comment by ronalddebakker** [comment]
But whatever one was searching for, stays in the box. Is it possible to run a search and then empty the box after pressing search and after pressing close?

Also when adding a product to a SO,  The focus will go back to the box.
However suddenly the pricebox stays empty and the quantitybox as well. 
The SO will not be saved.
This is not the case in the test environment.

**Comment by ronalddebakker** [comment]
New item is fine. Here is a screenshot after adding a product to the SO

![IMG_20190123_113202.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bed47df761bca00117e3944/125516c66e82c728ace21e0d46c1b9bd1cd0d3f8d6b9ee11f762a1c57a1477216b48e13b628ae92dbc56395b4d5a1cfd135f0d40f4f9897ea2e038708a590cee843e5e71972f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e3838d4c3718021b89fd5b27ed.jpg)

**Comment by jorr-it** [comment]
Second paragraph in new issue #192

**Comment by ronalddebakker** [comment]
I dont see a difference in the scanfield focus. I did refresh the browser

**Comment by jorr-it** [comment]
Sorry, I forgot to update the public web folder. Could you try again?

**Comment by ronalddebakker** [comment]
yes it is perfect now
