### ISSUE TITLE
[4h00m] Bulk edit

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#166]
At index pages, select multiple lines and bulk change status, location and attribute values.

**Comment by ronalddebakker** [comment]
this is also very usefull for the "zipcode" selection from another issue. ANWB needs this for routeplanning. So will we in time.

**Comment by jorr-it** [comment]
Turn off pagination when searching

**Comment by jorr-it** [comment]
Ronald, would you like this for stock only, or also PO and SO?

**Comment by jorr-it** [comment]
This issue is in progress...

**Comment by jorr-it** [comment]
@ronalddebakker You can test bulk edit and #166

**Comment by jorr-it** [comment]
<sub>Datum: Tue 29-1-2019 12:00<br />Gewerkt: 4h00m<br />Toelichting: en 168<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 57529086</sub>
