### ISSUE TITLE
Local user multiple locations

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#168]
Plus the functionality to assign postcodes to locations. And automatically assign locations to orders based on postcode of company.

**Comment by jorr-it** [comment]
@ronalddebakker In what cases do you want to assign an order to a location automatically? Only pickups and leergeld or also in internal created orders?

**Comment by jorr-it** [comment]
For me:

CREATE TABLE `nexxus`.`temp` (`user_id` INT NULL, `location_id` INT NULL);
insert into temp select id, location_id from usr;

**Comment by ronalddebakker** [comment]
pickups (PO) created externally and internally
Later we can add SO's

**Comment by jorr-it** [comment]
In the next test release this will be active. Please note: In the pickup form the hidden field for locationId should be removed when automatic location assignment is desired. Form field locationId will override the automatic assignment.

**Comment by jorr-it** [comment]
@ronalddebakker You can test #185 and #168 on copiatek.com

**Comment by jorr-it** [comment]
@ronalddebakker The bug we are currently experiencing is because previously we gave pickups a hardcoded location, while now it is flexible. This means also that a (pickup) order or product cannot be assigned to a location, just because the zipcode is unknown. Thus far location was a required property (and there are reasons for that). If we decide to make location an optional property of orders and products, we have to discuss and make sure what that means.

**Comment by ronalddebakker** [comment]
Can there be a switch in the admin panel? We will discuss how this functionality can or should work. Per haps:
Fixed location when internally creating a PO.
Flexible location depending on zipcode when creating a Pickup service by online form

**Comment by ronalddebakker** [comment]
when adding multiple locations to a local user, he does not see the location dropdown.
He will see all stock in those location though. The dropdown however should be there for him too.

**Comment by jorr-it** [comment]
Yes of course, I forgot make the dropdowns visible for local users. Will do!
