### ISSUE TITLE
Rename Standard to Gross Sales Price

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#170]
In creating a PO the sales price is named : Standard price. This is confusing to some, so best rename it to Gross Adviced Salesprice

**Comment by jorr-it** [comment]
@ronalddebakker 
Sleutelwoord is hier "sales", denk ik. Maar verder:
- Gross / bruto / netto zou ik vooralsnog vermijden, want de hele toepassing werkt nog niet met BTW. Deze term verduidelijkt niet, maar schept juist onduidelijkheid.
- Adviced Salesprice is niet goed Engels volgens mij, maar te letterlijker vertaald.

Ik stel voor om de term "Standard sales price" of "Sales standard price" te hanteren. Dat gebeurt verder overal al in de applicatie. Dit is de gangbare term.

Wat denk je daarvan?

**Comment by ronalddebakker** [comment]
Hi Jorrit
Dit lijkt mij uitstekend. "Standard sales price"
Dank je wel.


Van: Jorrit Steetskamp <notifications@github.com>
Verzonden: vrijdag 7 december 2018 09:18
Aan: Nexxus/NSK <NSK@noreply.github.com>
CC: Ronald De Bakker <ronald.debakker@copiatek.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Nexxus/NSK] Rename Standard to Gross Sales Price (#170)


@ronalddebakker<https://github.com/ronalddebakker>
Sleutelwoord is hier "sales", denk ik. Maar verder:

  *   Gross / bruto / netto zou ik vooralsnog vermijden, want de hele toepassing werkt nog niet met BTW. Deze term verduidelijkt niet, maar schept juist onduidelijkheid.
  *   Adviced Salesprice is niet goed Engels volgens mij, maar te letterlijker vertaald.

Ik stel voor om de term "Standard sales price" of "Sales standard price" te hanteren. Dat gebeurt verder overal al in de applicatie. Dit is de gangbare term.

Wat denk je daarvan?

**Comment by ronalddebakker** [comment]
In Nederland kennen we wel de verkoop adviesprijs of winkel adviesprijs die door de fabrikant wordt bepaald.
In het Engels heet dit eigenlijk de Retail Price (winkelprijs). We kunnen dan ook Recommended Retail Price hanteren. 
Hoe klinkt je dit in de oren?

**Comment by ronalddebakker** [comment]
It's good to think it through at this point. For the sake of flexibility there should be wholesale, retail ans sale pricing. Adding up existing attribute prices would be the wholesale price or list price. 

When applying discounts, there will be the retail price. Offering discounts can lead up to more and/or new customers. This complexity can also be used to clear some of the inventory.
In fact there is List price (e.g. what it is worth), Retail price (Suggested sale price) and Sale price (actual sale price) 

I am keeping in mind the future Point Of Sales and Webshop module where it will be very useful to differenciate between the List price (wholesale) and Sale price (retail).

It's already there too 
in product: Total price of attributes: € 0,00 (standard=list price and can be manually adjusted already)
in salesorder: Standardprice p.u. (=retail price)  This saleprice p.u. (= actual sale price)
Discount can be used for creating special prices for customers and resellers. To get rid of overstock for example
