### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#171]
Hierbij 2 screenshots waarbij de layout in de knoop raakt.
 
![reparatie-formulier-screen](https://user-images.githubusercontent.com/6950478/49720162-5e5c4c80-fc5f-11e8-9966-8ea0a61bd5e2.jpg)
![reparatie-formulier-papier](https://user-images.githubusercontent.com/6950478/49720163-5e5c4c80-fc5f-11e8-8f38-781507fad6ba.jpg)

**Comment by jorr-it** [comment]
@ronalddebakker Het is me een raadsel hoe je de opmaak van het eerste screenshot voor mekaar hebt gekregen. Kan je dat nog eens proberen en dan aan me uitleggen?

**Comment by jorr-it** [comment]
Agreement frames left/right ordered, so it fits on a page

**Comment by jorr-it** [comment]
Haha, that is one long word without a space somewhere! Please test it with some spaces, like normal text. Or tell how  long word like this should be wrapped.... ;-)

https://nl.lipsum.com/

**Comment by ronalddebakker** [comment]
Yes this looks much better lol.
Now just the signature boxes are still taking too much space. Agreement at order should be on de left half, and agreement after repair on the right side of the paper. the boxes can be way smaller and less high

**Comment by jorr-it** [comment]
Please make a simple drawing and send me a picture. That will spare some mails over and back.

**Comment by ronalddebakker** [comment]
[Uploading IMG_20190201_125737.jpg...]

**Comment by jorr-it** [comment]
How about now?

**Comment by ronalddebakker** [comment]
YES Perfect!
