### ISSUE TITLE
attributed products not in sold

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#173]
If I have a prodct "battery" for a laptop in stock and place it in a laptop and the laptop is sold, then the battery stock should be minus 1
This is not the case.

If I place the product monitor in stock, which is part of a laptop. and i add the monitor to the product "laptop" then the stock of the monitor should be minus 1. this is now not the case

thus the stock is not correct. 
This is about parts of a product (parts are: battery, adapter, replacement screen, which are also products) which are actually added as part of the product Laptop in stock

**Comment by jorr-it** [comment]
In the current model this is not possible. Example:
1. 10 laptops are purchased
2. 5 laptops of these 10 get an attributed product: battery
3. 3 laptops of these 10 get sold

Which of the 3 sold laptops have overlap with the 5 with new battery?

This question cannot be answered right now. We have to figure out a solution. Even more because the problem is a bit "bigger" than the reported bug.

**Comment by jorr-it** [comment]
Can we conclude that attributed products should be applied to all the products in the concerning bundle?

For example the bundle contains a quantity of 20 products. And the quantity of attributed products is 15; this can be considered "per unit". The total amount of attributed products is 300 in this example.

How about that?

**Comment by ronalddebakker** [comment]
I need to discuss this also with Mark and Timo to find out if this way is applicable for users in general.

**Comment by jorr-it** [comment]
Proposal will be build. I make a WIKI page for this.

**Comment by jorr-it** [comment]
In the new situation, attributed products will not have a quantity by default. In admin the quantity can be enabled. If you do, the entered quantity of the attributed product counts per unit. For example, if you enter 5 and the bundle consists of 20 products, then 100 attributed products are applied from stock.

**Comment by ronalddebakker** [comment]
This I have to see first before I understand :)

**Comment by jorr-it** [comment]
Go have a look:
http://copiatek.com/application

**Comment by ronalddebakker** [comment]
you will have to show me. I don't understand it very well.
