### ISSUE TITLE
how to handle created backorder?

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#175]
Add salesorder by form and a backorder PO is also created.
Now products are bought and added to the autogenerated PO and added to stock.

However I can not add these products to the existing sales order. 
As i want to add the product I can choose from a producttype. Then i need to fill out the same form as I already did in the PO.

It is not possible to add products from stock to the created SO (created by the online orderform)

Also changing the PO status from backorder to "order bezorgd" will not change the PO but will generate a new PO.

**Comment by ronalddebakker** [comment]
Sounds like a good idea

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by jorr-it** [comment]
@ronalddebakker We discussed this. Let me know what your followup is

**Comment by ronalddebakker** [comment]
now that we know to add products through the SO, we will go with that.
It makes sense for most users.
