### ISSUE TITLE
[1h00m] Leergeld bestelling formulier

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#178]

**Comment by jorr-it** [comment]
@ronalddebakker Het werkt, je kan het testen.

**Comment by jorr-it** [comment]
Nu hetzelfde voor de ophaaltest

**Comment by jorr-it** [comment]
<sub>Datum: Wed 9-1-2019 09:00<br />Gewerkt: 1h00m<br />Toelichting: #178<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 56465681</sub>

**Comment by jorr-it** [comment]
@ronalddebakker Could you please add "localhost" to the trusted domains of your reCaptcha? No extensions or prefix, just the word "localhost". Thanks!

**Comment by jorr-it** [comment]
@ronalddebakker The pickup form on your Wordpress site is working, except for one thing: file upload. For file upload the form I made uses the Uploadifive control. I can't get it to work in Wordpress. As I am not a Wordpress expert, I cannot fix this.

**Comment by ronalddebakker** [comment]
I looked in all the logs on the server but I cannot find any errors.
So i copied the code into a new html file on the server to exclude wordpress.
http://www.copiatek.nl/ophaaldienst.html but it still is not working. The problem  may be something else, like the upload restrictions on the nexxus server? copiatek.nl and nexxus.eco are on 2 different servers.
copiatek.com is on the same server as nexxus.eco

Also I noticed the below producttypes are not added to the form.
camera's
opslag
switches
psu
overig

I will look into the logs of nexxus server.

**Comment by ronalddebakker** [comment]
also on nexxus, no erros in logs. then I put the form on http://copiatek.store/ophaal.html
there is no wordpress at all on that domain. Helas it doesn't upload files (small jpg) either
So I think the upload script isn't working at the moment.

**Comment by jorr-it** [comment]
<sub>Datum: Fri 11-1-2019 12:00<br />Gewerkt: 3h00m<br />Toelichting: niet declarabel<br />Bijzonderheden: Dit werk wordt niet gedeclareerd.<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 56645429</sub>

**Comment by jorr-it** [comment]
<sub>Datum: Fri 11-1-2019 15:00<br />Gewerkt: 2h00m<br />Toelichting: pickup<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 56645434</sub>

**Comment by ronalddebakker** [comment]
I can see uploads in nexxus/var/uploads but these files have no extension, like .pdf or .jpg

**Comment by jorr-it** [comment]
> also it doesn't go to the thank you page after submitting..
> onclick"location.href("http://www.copiatek.nl/bedankt");">Send

This is the wrong way (and secondly misses an equal sign anyway). I will fix that.

> Also I noticed the below producttypes are not added to the form.

Producttypes  have to be manually added in HTML, as there is no API for this to load dynamically yet.

> Can it have anything to do with cross domain uploads?

I'll have a look.

**Comment by ronalddebakker** [comment]
the producttypes from nexxus are in the html but there is no submission (like: overig). 
I can ask Ryan to check this again, per haps it is a spelling error in his code or something.

**Comment by jorr-it** [comment]
Cross domain uploads is not an issue.

The test form on Wordpress is working, also upload. Things I did:

- </form> end tag was missing
- location href to thanks page in jquery not in html
- removed lots of HTML crap around both file input controls; why was this added anyway?

> the producttypes from nexxus are in the html but there is no submission (like: overig).

PHP is case sensitive, so this is not correct:

id="pickup_form_qoverig" name="pickup_form[qoverig]"

**Comment by ronalddebakker** [comment]
Yes you are correct with case sensitive. i changed 3 names according to producttypes and these are now working. I will do the other ones as well later today.

After submitting I got:
Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server. However the form was delivered into nexxus. but i didn't see the thanks page which is obvious due to this error 
Also i dont know where the image is. This is the PO 2019000198

**Comment by jorr-it** [comment]
Probably fixed. Could you try ophaaldiensttest again?

**Comment by ronalddebakker** [comment]
Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server.

Ill send an email with the content of post

**Comment by ronalddebakker** [comment]
you are right. If I use this form from copiatek.store/oph.... and with edge browser, I also dont have this issue.
So I think it is my chrome browser problem, per haps ad blocker. I will look into it because it may be more common. Or its just the cache...

I will put this form live now. Is there a way I can look at the uploaded images in Nexxus (PO)?

**Comment by ronalddebakker** [comment]
okay so this was my browser and it is now working fine. Form is live \o/

Is there a way I can look at the uploaded images in Nexxus (PO)? Or shall we make a new issue for this? if uploading a pdf doc, there is some html code in the PO but 500 error when clicking on it.

**Comment by jorr-it** [comment]
Bug! Please make a new issue, thanks

**Comment by jorr-it** [comment]
<sub>Datum: Sat 12-1-2019 11:00<br />Gewerkt: 1h00m<br />Toelichting: Wordpress fixing<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 56657901</sub>
