### ISSUE TITLE
[3h00m] Pickup with addresses

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#185]
Per address the products

**Comment by ronalddebakker** [comment]
yes. the supplier has his own address. but adding multiple pickup locations seems very usefull for schools and bigger organisations like capgemini. 
The supplier needs to be able to add multiple pickup addresses and add products per pickup location

**Comment by jorr-it** [comment]
Let's talk about addresses to avoid confusion with location objects in application.

**Comment by jorr-it** [comment]
<sub>Datum: Fri 25-1-2019 09:30<br />Gewerkt: 3h00m<br />Toelichting: en #168<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 57364072</sub>

**Comment by ronalddebakker** [comment]
i contacted a zzp'er and a company, till now no one wants to or can build the extra functionality.
