### ISSUE TITLE
unclear submission in form

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#187]
this seems like a bug and the information provided is really important to have.

**Comment by ronalddebakker** [comment]
I dont see the answer for datadestruction, no photo is visible and uploaded contract seems like a broken link

![PO-unclear_uploads.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bed47df761bca00117e3944/125516c66e82c728ace21e0d46d8bbd7368c80a58ae8ad7cb14dfc9b284234316546b3397f8fe62bab0021435a0d1ffe460a5b4cfcf9dc2ff0b23c708f5b08b8826c5a25d42103eee9dc4be05ce36ade0d97bcae8b44cae93821e0828f4c381e07198df84f78.jpg)

**Comment by jorr-it** [comment]
Actually "Statement" is the type of destruction. I translated "Vernietigingsverklaring" to Statement. Apparently it is to cryptic. ;-)

The cryptic agreement file name will be fixed in next test release. But not with terugwerkende kracht.

**Comment by jorr-it** [comment]
Foto's moeten nog thumbnails krijgen

**Comment by ronalddebakker** [comment]
when submissing a form (http://copiatek.com/application/ophaaldienst) I get this error:

<!DOCTYPE html> <html> <head> <meta charset="UTF-8" /> <title>An Error Occurred: Method Not Allowed</title> </head> <body> <h1>Oops! An Error Occurred</h1> <h2>The server returned a "405 Method Not Allowed".</h2> <div> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. </div> </body> </html>

**Comment by jorr-it** [comment]
That URL does not exist (anymore). You should test with:

http://www.copiatek.nl/ophaaldienst/
or
http://www.copiatek.com/application/public/pickup

**Comment by ronalddebakker** [comment]
Ah yes this form is correct. Destruction statement is fine now.

I think below is for next release?
PDF is a broken link
images is not visible

**Comment by ronalddebakker** [comment]
yohoo :D perfect
