### ISSUE TITLE
selectbox preview gone after update

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#188]
as title

**Comment by ronalddebakker** [comment]
![selectbox-preview.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bed47df761bca00117e3944/125516c66e82c728ace21e0d46fb9196268197ab80f1f253b658e69d2c51653f6b14b1247a80e03cfd1839540d0e1cab135c5744fcac8d7da2b63c758d5f5ebed0680e66da2f53fde6d640e258f075c95d8fa4be8846c1ed3922ee838b4c371e061d8ced10.jpg)

**Comment by ronalddebakker** [comment]
no. 
I mean the green tiptool, it was working fine but now it only works for txt box and not select box. See Processor Model=fine others are not fine anymore.

**Comment by jorr-it** [comment]
Sorry, got it now

**Comment by ronalddebakker** [comment]
I can see now the data of the select box, but not the label. Like-> "PC Model: SFF" will only show SFF. With a txt input it will show the label and the entered data, like -> "Processor: Intel" 
I guess this will do, but if it is not too much work and simply done, I would prefer to see both.

**Comment by jorr-it** [comment]
What do you mean by label? I think there is no more data to show. The tooltip preview shows same info as the edit screen does.

**Comment by ronalddebakker** [comment]
here is an image you can compare with the previous image. you will see what i mean :)
![tooltip.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bed47df761bca00117e3944/125516c66e82c728ace21e0d46fc9b952f968ab9cda5fd53b652fa912a5265296b51a12a72d2e17ce7122b045b094aac415d5847a9aa882ef7a42062c80d55b98e30063e937f03a6aa8317b500bf24834d86b0ba8a48c7e83837aa.jpg)

**Comment by jorr-it** [comment]
Got it :-)

**Comment by ronalddebakker** [comment]
perfect
