### ISSUE TITLE
[7h00m] Bulk Print Function

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#191]
Print multiple barcodes and also print multiple pricecards at once. Also print multiple checklists.

**Comment by jorr-it** [comment]
<sub>Datum: Thu 13-6-2019 09:00<br />Gewerkt: 7h00m<br />Toelichting: #228 #226 #227 #77<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 64573797</sub>

**Comment by jorr-it** [comment]
<sub>Datum: Fri 14-6-2019 08:00<br />Gewerkt: 2h00m<br />Toelichting: #228 #77<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 64619113</sub>

**Comment by jorr-it** [comment]
@ronalddebakker De bug met bulk print checklists is opgelost op nexxus.eco

**Comment by ronalddebakker** [comment]
currently I can also bulk print in PO and SO page, but there is a 500 error. It would make sense if I could bulk print barcodes and PO/SO orders, but not checklist and pricecards :)

![image](https://user-images.githubusercontent.com/39778046/59869747-5dd20a80-9394-11e9-8a5a-c22924ef69a1.png)

**Comment by jorr-it** [comment]
<sub>Datum: Thu 20-6-2019 11:00<br />Gewerkt: 1h00m<br />Toelichting: #191<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 64927065</sub>
