### ISSUE TITLE
[3h00m] SO not valid error

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#192]
when adding a product to a SO, The focus will go back to the box.
However suddenly the pricebox stays empty and the quantitybox as well.
The SO will not be saved.
This is not the case in the test environment.

**Comment by jorr-it** [comment]
![so adding article](https://user-images.githubusercontent.com/6950478/51604617-9cf74f00-1f0d-11e9-8360-c73ac27f7c2f.jpg)

**Comment by jorr-it** [comment]
Ronald came back on this bug, so I prioritized it from the inbox. 

Sometimes the page keeps loading. It gets into an endless loop. This seems the same bug. After a redirect the method isSubmitted stays true.

**Comment by jorr-it** [comment]
@ronalddebakker This is fixed, also on nexxus.eco

**Comment by ronalddebakker** [comment]
I noticed today. Great news. If its in de code I can also update the other sites.

**Comment by jorr-it** [comment]
Yes, you can :-)

**Comment by jorr-it** [comment]
<sub>Datum: Wed 6-2-2019 09:00<br />Gewerkt: 3h00m<br />Toelichting: long search, small fix<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 57948471</sub>
