### ISSUE TITLE
create batches from multiple PO's / SO's

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#194]
Er moeten batches van inkooporders gemaakt kunnen worden. 
Een batch is een groep van inkooporders die aan elkaar zijn gekoppeld om in een keer aan te kunnen bieden aan chauffeurs op een locatie. 

De batch opdracht wordt aangeboden, geaccepteerd en afgerond door chauffeurs in de app, waar na de inkooporders van de batch van status veranderd worden d.m.v. de API.

**Comment by ronalddebakker** [comment]
this seems familiar with #2 in the icebox.

**Comment by jorr-it** [comment]
Batches principle will be cancelled, batching can occur by "status pool".
