### ISSUE TITLE
API for batches (194)

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#195]
This is the API part for #194

- API: Batches moeten aangeboden, geaccepteerd en afgerond kunnen worden via de API. Het meest essentieel is een lijst van batches kunnen ontvangen via de API (met inkooporders inbegrepen), dan kunnen inkooporders eruit gelezen worden en qua status aangepast worden.

**Comment by jorr-it** [comment]
Eventually it concerns two functionalities:
- Add new product(s)
- Change product quantity
