### ISSUE TITLE
[3h00m] API: Update product (quantity)

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#196]
is related to #195

- API: Functies voor het wijzigen van de inkooporder inhoud. Bij het afronden van orders moeten er producten bij en af kunnen gaan.

When a PO is created by the form (or otherwise) a number of products is added to the PO.
After picking up the products and delivering them to the wharehouse, there may be a different number of products (for whatever reason).

Via the app it should be possible to change/correct the number of products within a PO

**Comment by jorr-it** [comment]
Eventually it concerns two functionalities:
- Add new product(s)
- Change product quantity

**Comment by jorr-it** [comment]
Third functionality: Change location of order

**Comment by jorr-it** [comment]
Quantity update is a PUT comparable with the existing status update.
URL is: api/purchaseorderstatus
Form data parameters are: purchaseOrderId, productId, quantity

Location update is a PUT too.
URL is: api/purchaseorderlocation
Form data parameters are: purchaseOrderId, locationId

Product creation is a POST
URL is: api/product
Form data parameters are: 
- sku (if not delivered, it will be created automatically)
- name (required)
- retailPrice (in euro, for example 12.34)
- purchasePrice (in euro, for example 12.34)
- description 
- purchaseOrderId (required)
- quantity 
- typeId  (required)
- statusId 
- locationId  (if not delivered, location of PO will be taken)

Product creation interface has no facilities for filling attributes yet. If desired, please let me know and we can discuss. I would suggest to first implement the six functions (3 old and 3 new).

**Comment by jorr-it** [comment]
<sub>Datum: Fri 8-3-2019 10:30<br />Gewerkt: 3h00m<br />Toelichting: #196<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 59541202</sub>

**Comment by ronalddebakker** [comment]
i have no idea how to test this. Will follow up much later

**Comment by jorr-it** [comment]
True, you cannot test this. You can only test the app functionality using this API function.
