### ISSUE TITLE
bulk edit bug?

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#209]
I updated the demo site demo.nexxus.eco/nsk
The bulk edit "select all" is not working in chrome nor Edge.
Can not bulk change location.

Also I see in admin/attributes a dropdown Locations. Not sure why that is introduced :)

**Comment by ronalddebakker** [comment]
the bulk function works fine in production and in test though. All sites are on the same server with php 7.0.33
Any suggestions?

**Comment by jorr-it** [comment]
Two suggestions:
- Did you copy files from the web folder to the public_html folder?
- Did you do shift-refresh?

**Comment by ronalddebakker** [comment]
yes thanks it was the contents of the web folder
