### ISSUE TITLE
[5h00m] add calendar

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#210]
Somehow this functionality was lost somewhere  along the way.
All pick up orders have colors depending on their status; orange, blue, green
They also have a flag depending on the destruction methods. Red flag when Killdisk or Declaration is needed.

We need to think about the rights (user roles), i.e. who can change the preferred pick up dates for example.

Currently we use Outlook but it is a workaround and confusing

**Comment by jorr-it** [comment]
Pickup date needs to be editable in edit screen of order.

**Comment by jorr-it** [comment]
Een eerste versie van de logistiek kalender is te testen op copiatek.com.

De volgende zaken zijn gemaakt:
- Per pickup order is de pickup date en een logistics medewerker in te stellen.
- Per order status is een kleur in te stellen (in admin)
- De rol LOGISTICS is toegevoegd. Deze rol (en managers en admins) hebben een Logistiek optie in het hoofdmenu gekregen.
- Een weekweergave is gemaakt met alle pickup orders van afgelopen week tot komend jaar.

De kalender zal nog niet zijn volgens wens. Mijn verwachting is dat de wensen concreet worden als ermee getest zal zijn.

Om deze update te installeren op een andere server, is een composer update nodig.

**Comment by jorr-it** [comment]
<sub>Datum: Thu 25-4-2019 10:00<br />Gewerkt: 5h00m<br />Toelichting: #210<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 62020226</sub>

**Comment by jorr-it** [comment]
<sub>Datum: Fri 26-4-2019 09:00<br />Gewerkt: 1h00m<br />Toelichting: #210<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 62063828</sub>
