### ISSUE TITLE
Error 500 check from log

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#211]

**Comment by ronalddebakker** [comment]
voorraad pagina; location loods 126; status op voorraad gezet lijkt opgelost. Maar status inschrijven geeft nog fout 500

**Comment by jorr-it** [comment]
De voorraad pagina toont attributen van een product in een tooltip. Er kon wat misgaan bij die tooltip als een attribute een dropdown is maar leeg. Bug is gefixed bij volgende test release.
