### ISSUE TITLE
[2h00m] combine into 1 dropdown

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#215]
In stock overview combine the below options into a single dropdown to be able to see a certain selection.

Purch	
Stock
Hold	
Sale	
Sold

**Comment by jorr-it** [comment]
<sub>Datum: Tue 16-4-2019 10:00<br />Gewerkt: 2h00m<br />Toelichting: en meer<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 61634711</sub>
