### ISSUE TITLE
[3h00m] Be able to split a bundle when sold

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#216]
Discussed over the phone.
salesorder is created as a backorder.
Product is entered. Quantity is 20.
Bundle needs to be split but is not possible because it is already in/as Sold.

We need to be able to individualize the bundle when there is a SO as a Backorder.

**Comment by jorr-it** [comment]
I think we can say that the request is to be able to split a sold bundle. It is independent from being back order or not.

**Comment by jorr-it** [comment]
After discussion we concluded that user has this possibility already. If product status has IsStock checked, then you are able to split.

**Comment by jorr-it** [comment]
Split form needs an option to individualize whole bundle, also sold products.

**Comment by jorr-it** [comment]
<sub>Datum: Wed 17-4-2019 12:00<br />Gewerkt: 3h00m<br />Toelichting: #216<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 61757337</sub>

**Comment by ronalddebakker** [comment]
seems fine after testing a sold bundle.

**Comment by jorr-it** [comment]
<sub>Datum: Fri 19-4-2019 09:00<br />Gewerkt: 2h00m<br />Toelichting: #216<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 61865935</sub>
