### ISSUE TITLE
[1h00m] create a field in a PO so the origin (like a url) can be entered

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#217]
The pickup form will be published at partner company websites. We want to know were a pick up form has its origin in the form of a url for example.

**Comment by ronalddebakker** [comment]
Also! In the new pickup form - concerning Extra Pickup address - not only address is used but also Zipcode, province and city. 
See the form here: https://copiatek-pickup.proofit.ly/

Per haps this needs extra fields in the backend?

**Comment by ronalddebakker** [comment]
can not see the field yet.

**Comment by jorr-it** [comment]
Field is made visible. Let me know if I can publish to .eco.

**Comment by jorr-it** [comment]
<sub>Datum: Tue 23-4-2019 09:30<br />Gewerkt: 1h00m<br />Toelichting: #217<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 61867184</sub>
