### ISSUE TITLE
Pickup addresses

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#218]
De adresgegevens voor het eerste extra ophaal adres, worden als volgt in het formulier gezet:

pickup_form[q1Straat]: Schadijk 15
pickup_form[q1Postcode]: 8888AA
pickup_form[q1Provincie]: 
pickup_form[q1Stad]: Veenendaal

In Nexxus the Address0 and Address1 are shown. it probably misses fields?
per haps Imad can call Jorrit on tuesday 23-4 to determine what exactly needs to be done on which end.

**Comment by jorr-it** [comment]
These fields are used in the supplier object. Each supplier has street, zipcode, city and state. Probably the Javascript of Imad converts Dutch names like "straat" to "street" before sending to the API.

**Comment by ronalddebakker** [comment]
the fields for extra addresses you made are:  Address0, Address1 etc. 
I think there should then be 1 label in the front formular where all data is filled out by the supplier. 
Like: Kerkstraat 7, 2500AA, Den Haag ZH
