### ISSUE TITLE
Pickup sorting by address

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#224]
when supplier adds multiple pickup addresses, the sequence of products should be rearranged per pick up address.

perhaps a dropdown to select a certain pickup address.
[po-2019000495.pdf](https://github.com/Nexxus/NSK/files/3127180/po-2019000495.pdf)

see: Purchase order 2019000495 in nexxus.eco

**Comment by jorr-it** [comment]
Products list in PO edit scherm sorteerbaar maken per kolom

**Comment by jorr-it** [comment]
Sortering clienside with jquery datatables

**Comment by jorr-it** [comment]
This will be combined with issue #324
