### ISSUE TITLE
[2h00m] Supplier/Customer dropdown for local users

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#228]
Dropdown in orders shows all companies, not only own

**Comment by jorr-it** [comment]
aaltense.uitdaging
6x een 5

**Comment by jorr-it** [comment]
@ronalddebakker Dan blijven we met het probleem wat te doen als een local/logistics user een order opent van zijn locatie met een supplier/customer met een "buitenrechtelijke" locatie. Hoe zou je dit willen oplossen?

**Comment by ronalddebakker** [comment]
- ik denk dat de customer/supplier per definitie niet tot een locatie hoeft toe te behoren, maar wel aan een inkoop of verkooporder. De meeste suppliers hebben geen locatie. De klanten wel
- Per definitie behoort een inkooporder  wel toe aan een locatie. Moet dat eigenlijk wel voor een SO? het mag wel wat mij betreft.
- Daarentegen kan een product tot een andere locatie behoren dan de in of verkooporder.

De customers/suppliers kunnen en mogen in feite aan elke locatie toegekend worden als daar een behoefte toe is of aan geen enkele. Maar dan krijgen we de "bug" terug. Die moet dan uiteindelijk worden opgelost met de fulfillment module.

**Comment by jorr-it** [comment]
<sub>Datum: Mon 17-6-2019 17:30<br />Gewerkt: 2h00m<br />Toelichting: en #235<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 64749880</sub>
