### ISSUE TITLE
Checklist empty

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#235]
Als ik een aantal checklist ga printen is er ineens geen inhoud.
Zie product sku 1560782610.

Verder als ik online de checklists heb ingevuld, van todo naar done. Dan print deze aanvullingen niet mee. Maw ik krijg dan weer een lege checklist.
Zie product sku 1560782621

**Comment by jorr-it** [comment]
@ronalddebakker 

Als ik de checklist van sku 1560782610 open, dan is het niet leeg. Ik kan het dus niet reproduceren. Hoe heb je dit voor elkaar gekregen? Bestaat het nog?

De vinkjes opnemen in de print, zoals je wilde aantonen met sku 1560782621, dat heeft überhaupt nog nooit gewerkt. Ik heb het nu gemaakt.

**Comment by ronalddebakker** [comment]
De vinkjes opnemen in de print, - Ja dit is nu prachtig.

ik schrijf: Als ik een aantal checklist ga printen
jij schrijft: Als ik de checklist van sku 

Het gaat echt om het selecteren van meerdere sku's en dan de bulk print functie gebruiken
ik selecteer nu 5 sku's en print. Dan maakt ie 4 pagina's. Alleen de taken zijn te zien in de sku waar een aantal hokjes zijn aangekruist. zie pdf
[checklist-4.pdf](https://github.com/Nexxus/NSK/files/3298687/checklist-4.pdf)
