### ISSUE TITLE
[1h00m] People are uploading images but it is not visible anymore in the PO.

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#245]
Did anything change? Is it a bug? Or did something go wrong during upload?

in copiatek.com/application it is still working fine

**Comment by jorr-it** [comment]
<sub>Datum: Mon 22-7-2019 11:00<br />Gewerkt: 1h00m<br />Toelichting: #245<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 66444686</sub>

**Comment by jorr-it** [comment]
Symfony formulier werkt wel, Vue formulier werkt niet
