### ISSUE TITLE
Enrich pickup form

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#246]
- Multiple addresses, more than 4, reactive, like pickupform.copiatek.nl
- Embedding with jQuery

**Comment by jorr-it** [comment]
Geen beperking van 4 adressen, moet meer kunnen zijn

**Comment by jorr-it** [comment]
Explanation in wiki:
https://github.com/Nexxus/NSK/wiki/Pickup-form

**Comment by ronalddebakker** [comment]
This looks very good and simple enough.

2 questions though.
1 When I add an extra address, where/how can I add materials for that 2nd address?
2 Default options, is unclear to me where to put this code. Should it be on the same page as the HTML code?

**Comment by jorr-it** [comment]
1. In the second (or third or ...) column

![image](https://user-images.githubusercontent.com/6950478/78371359-27364b00-75c8-11ea-9af6-7fdd1ae76a04.png)

2. If you want to deviate from the default settings, you can put one or more of them inside the backets of nexxusPickup() as you can see in the example. This is usual practice with jQuery plugins.

**Comment by ronalddebakker** [comment]
oh, i see it now, very nice.

A few producttypes should not be in the form, such as Accu Laptop, Monitor Laptop and Inpakmateriaal.
In drop down HDD wipe report Killdisk a €3,50 should now be 
HDD certified wipe report a €3,50

For 2 I added the code but I had to change the ' ' things to make it work. I have adjusted the wikipage.

**Comment by ronalddebakker** [comment]
1. have a look at PO #2020000042 as not all data came through. Origin for example. jpg and pdf also not 
2. also i wonder if i have the original pickup (main) addres and 1 extra address, how should the form be filled?
3. For the extra address can there be 3 fields instead of 1? (Straat + nr * and Postcode and Woonplaats *)

**Comment by jorr-it** [comment]
1. Bug with origin field is fixed. I don't experience any problems with attachments. Please share the URL of your pickup form implementation with me.
2. You should set "Aantal ophaaladressen" to two and enter both addresses, unregarding if one of them is same as company address or not. If this is not convenient enough, let me know, I have another idea.
3. Yes, that is possible of course, but it will be pointless, as the address fields will be merged immediatelly after submit into one line (into the product name). If you want it anyway, let me know and I will make it like that.

**Comment by ronalddebakker** [comment]
1 great I will look later. i use https://ophaalformulier.copiatek.nl
2 we'll see how people will experience it. for me it was a little confusing.
3 the only point is clearity to the clients. if they see 1 line, they won't know they should fill in also required zipcode and city. in the past they have filled in the address and I have to assume then it is in the same city as the main address :)

**Comment by ronalddebakker** [comment]
the result
![image](https://user-images.githubusercontent.com/39778046/78503253-c8a6d380-7765-11ea-85b9-364b8de68ac9.png)

**Comment by jorr-it** [comment]
1. Thanks for the link, I fixed the issue
2. ... and 3. Just give me the order and I'll improve it :-)

**Comment by ronalddebakker** [comment]
1 great, will test tomorrow
3 yes please improve :)

**Comment by jorr-it** [comment]
The pickup address field is split into three fields.

BTW: It is unlikely that the numbers in the jQuery settings need quotes. I changed the wiki back. If you really experience problems when using numbers without quotes, please let me look with you, we have to find the cause.
