### ISSUE TITLE
Verzendlijst importeren

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#256]
Verzendlijst:
https://www.copiatek.nl/leergeld-bestelling/

Import van verzendlijst maakt voor elke regel een lege SO aan. Bij uploadform ook keuze van betreffende partner. En misschien meer. Geen producten, dat doet medewerker naderhand.

**Comment by jorr-it** [comment]
Ronald schreef: als ik een verzendlijst upload in de test omgeving voor Alblasserwaard, dan worden de salesorders aangemaakt op naam van Leergeld Arnhem. Ik snap niet goed waarom, maar het lijkt me nog niet zo goed functioneren.

**Comment by jorr-it** [comment]
As part of issue #256 the procedure to see if delivered company details already exists is rewritten. I suspect that to fix this issue too. Please test.

**Comment by ronalddebakker** [comment]
uploading a xls list at http://copiatek.com/application/salesorder/import returns error 500

**Comment by jorr-it** [comment]
The list you used had no Bedrijfsnaam value. This exception is handled now, you can test.

**Comment by ronalddebakker** [comment]
see mail. in now empty 'bedrijfsnaam' there should automagically be the partner where I import the csv file.

**Comment by ronalddebakker** [comment]
met 1 adres in de csv en 1 partner in het systeem lijkt dit nu perfect.
