### ISSUE TITLE
purchaseorder wrong supplier

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#257]
A new supplier submitted a pickup via copiatek.nl/ophaaldienst (2019001158) 
for some unknown reason it was added to a existing supplier (PSG)
I created the correct supplier manually and changed the name in the Purchase menu

This is not the first time it happend and it seems totally random. 
Per haps more fields need to be checked to see if the supplier already exists or a new supplier is created by the form. Companyname and Email or address for instance instead of only companyname

**Comment by jorr-it** [comment]
Search for existing supplier is improved. This can be tested in test environment.

**Comment by jorr-it** [comment]
match moet worden:
- naam en postcode en huisnummer; of
- email en postcode; of
- telefoonnr en postcode

Postcode is nodig omdat één leveranciersnaam kan meerdere vestigingen hebben bijvoorbeeld.

**Comment by ronalddebakker** [comment]
this can only be really tested when the new pickupform is active.
