### ISSUE TITLE
login for partner

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#259]
when a customer/supplier has role partner, then they can not log into the system.
so i have to make them a local user and create a location, also i need to set PO/SO and articles to that location.

continueing work on the module is needed. :)

**Comment by jorr-it** [comment]
This is not a bug. Currently we have two things:
- A customer can be configured to be a partner
- A user can be configured to have role "partner"

So when you write "when a customer/supplier has role partner", that is wrong. A customer cannot have a role, only a user can have a role. (Secondly a supplier cannot be a partner.)

I guess what you are asking to make it possible to relate a user with role "partner" with a customer being a partner. This can happen by giving the customer-partner and the user the same location.

Please try this logic. If it does not work (to your liking), then let's have a chat. :-)

**Comment by jorr-it** [comment]
Now locations are removed from most classes ( #262 ) we can make this issue like it should.

**Comment by ronalddebakker** [comment]
this is solved. while the owning partner keeps seeing their own products dispite of the location of a product.
