### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#263]
reCaptcha stond uit, nu weer aangezet. We moeten goed controleren of dit geen problemen gaat opleveren.

**Comment by ronalddebakker** [comment]
where can i find this recaptcha?

**Comment by jorr-it** [comment]
If you want to test this with the new location /nsk, you have to install a form somewhere which posts to the new location.

**Comment by ronalddebakker** [comment]
I have a new site:  https://ophaalformulier.copiatek.nl/
it is the existing form currently, but I would be great to put your modified form in here. This is another issue, i have to look which one it is.

**Comment by jorr-it** [comment]
The hyperlink in your last comment does not work.

**Comment by ronalddebakker** [comment]
it works again. php version was too high

**Comment by ronalddebakker** [comment]
it is secure url https I had to click 2x before i got the page.
 https://ophaalformulier.copiatek.nl/

**Comment by jorr-it** [comment]
This issue is obsolete now we will get new method (check out #246)
