### ISSUE TITLE
Sales order form with jQuery

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#277]

**Comment by ronalddebakker** [comment]
pc set 149,-
basis laptop 225,-
geavanceerde laptops 349,-
nieuwe laptop 549,-

**Comment by jorr-it** [comment]
@ronalddebakker You can define products and prices in your implementation. Parallel to my work you can already study and implement:

https://github.com/Nexxus/NSK/wiki/Public-forms

**Comment by jorr-it** [comment]
@ronalddebakker You can test and implement. Please note the small changes to wiki: productTypeId parameter is removed, remark parameter is added.

**Comment by ronalddebakker** [comment]
i made a test and it is working www.copiatek.nl/leergeld
later per haps we can enrich
