### ISSUE TITLE
Split error

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#293]
When split=whole bundle+create new sku dan is er 12x ge-individualiseerd
maar kijke je in de PO dan is er een splits maar ook het originele artikel heeft de normale volle bundel als je rechten gelijk is aan local

**Comment by jorr-it** [comment]
@ronalddebakker Heb je binnenkort een moment om dit aan mij te demonstreren? Je kan dan je beeld delen met Teamviewer of Skype.

**Comment by ronalddebakker** [comment]
Hoi Jorrit
Jawel maar dat probleem zit hem bij Jacqueline, die minder rechten heeft.
Zij werkt niet op woensdag. Andere dagen van 0900 tot 15.30uur

Zeg maar wanneer het jou uitkomt.
Gr ronald

Van: Jorrit Steetskamp <notifications@github.com>
Verzonden: dinsdag 22 september 2020 11:17
Aan: Nexxus/NSK <NSK@noreply.github.com>
CC: Ronald De Bakker <ronald.debakker@copiatek.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Nexxus/NSK] Split error (#293)


@ronalddebakker<https://github.com/ronalddebakker> Heb je binnenkort een moment om dit aan mij te demonstreren? Je kan dan je beeld delen met Teamviewer of Skype.

**Comment by jorr-it** [comment]
Dit bleek geen bug te zijn.
