### ISSUE TITLE
add barcode to POharacters so it will fit nicely.

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#314]
where the name of the client is. With a maximum number of characters so it will fit nicely.

**Comment by jorr-it** [comment]
Barcode of supplier.name on purchaseorder/print

**Comment by jorr-it** [comment]
@ronalddebakker This is implemented and live.  Barcode currently has a max of 50 characters. Let me know if this needs to be more or less.

**Comment by ronalddebakker** [comment]
Van: Jorrit Steetskamp <notifications@github.com>
Verzonden: maandag 11 januari 2021 14:51

This can be shortened to 20 characters, else it will fall from the page 😊


Aan: Nexxus/NSK <NSK@noreply.github.com>
CC: Ronald De Bakker <ronald.debakker@copiatek.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Nexxus/NSK] add barcode to POharacters so it will fit nicely. (#314)


@ronalddebakker<https://github.com/ronalddebakker> This is implemented and live. Barcode currently has a max of 50 characters. Let me know if this needs to be more or less.
