### ISSUE TITLE
Combobox

### ISSUE THREAD

**Issue by nebbii** [Nexxus/NSK#45]
Dropdowns that could potentially become very big should have some sort of search feature that allows them to type the name of the entity they want to receive.

**Comment by jorr-it** [comment]
Sales order : Add product

**Comment by ronalddebakker** [comment]
I can type the name of the product but not scan the SKU. Is this also possible? If I sell 5 articles with barcodes, they will one by one be added to the salesorder. like product scanning at the grocery shop

**Comment by jorr-it** [comment]
Sure! I move this issue back to column In Progress
