### ISSUE TITLE
Delivery page with signature

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/NSK#48]
Coolblue has a great system actually. 
When a product is sold, it will likely be handed-out personally. In that case someone should add a signature for confirmation of receiving goods (tablet/smartphone).
In case of ANWB someone will transport bikes between locations. It must be possible to administer this easily through the app.

**Comment by jorr-it** [comment]
Ronald, is this the same document as the pickup print we discussed this week?

**Comment by ronalddebakker** [comment]
This is the confirmation of delivery. DHL PostNL etc work with some smartphone where the receiver can sign for receiving the package

**Comment by jorr-it** [comment]
@ronalddebakker Could you please make a template for me?

**Comment by ronalddebakker** [comment]
[2021-01-26-delivery-nexxus.pdf](https://github.com/Nexxus/NSK/files/5873364/2021-01-26-delivery-nexxus.pdf)
