### ISSUE TITLE
Individualize / split product bundles

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#88]

**Comment by jorr-it** [comment]
In de stock pagina hebben productbundels een grijze knop in de rij gekregen. Als je daarop klikt, verschijnt een formuliertje om een bundel te spitten. Je kan bijvoorbeeld 40 producten van een bundel afsplitsen en direct een andere status geven. Als je individualize aanvinkt, krijg je 40 aparte regels.

De nieuwe bundel komt ook op de purchase order te staan. De nieuwe bundel neemt attributen van de oude bundel over, behalve toegepaste onderdelen (attributed products).

**Comment by ronalddebakker** [comment]
dit is echt ontzettend mooi

**Comment by jorr-it** [comment]
Mooi zo. Ik zal nog een korte toelichting maken in de popup
