### ISSUE TITLE
[15h00m] Repair, services, tasks, checklists

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#91]

**Comment by jorr-it** [comment]
Vervangend apparaat, back-up, onderzoekskosten; deze velden van het ICT Waarborgformulier worden tasks in Nexxus.

**Comment by jorr-it** [comment]
Repair kan zorgen dat product wel op voorraad komt, zonder dat er een purchase aan vooraf is gegaan.

**Comment by jorr-it** [comment]
Product::getQuantityRepairing  // to do: and is not done

**Comment by jorr-it** [comment]
<sub>Datum: Mon 12-11-2018 10:30<br />Gewerkt: 2h00m<br />Toelichting: start<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 54014845</sub>

**Comment by jorr-it** [comment]
With this update, Doctrine is not capable of doing the update automatically. Use --dump-sql and modify the script.

At start of script:

rename table service to aservice;

Somewhere in the middle of the script:

ALTER TABLE product_order ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE aservice ADD CONSTRAINT FK_E19D9AD23256915B FOREIGN KEY (relation_id) REFERENCES product_order (id);
CREATE INDEX IDX_E19D9AD23256915B ON aservice (relation_id);

These mutations ons aservice must come *after* mutations to product_order

**Comment by jorr-it** [comment]
<sub>Datum: Wed 28-11-2018 15:00<br />Gewerkt: 2h00m<br />Toelichting: Services en repair<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 54771492</sub>

**Comment by ronalddebakker** [comment]
I am getting this error:

Failed to execute SQL : SQL CREATE TABLE aservice (id INT AUTO_INCREMENT NOT NULL, relation_id INT DEFAULT NULL, task_id INT DEFAULT NULL, status INT NOT NULL, description LONGTEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, price INT DEFAULT NULL, INDEX IDX_5923AE03256915B (relation_id), INDEX IDX_5923AE08DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB; ALTER TABLE product DROP discr; ALTER TABLE product_order DROP PRIMARY KEY; ALTER TABLE product_order ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY; ALTER TABLE aservice ADD CONSTRAINT FK_5923AE03256915B FOREIGN KEY (relation_id) REFERENCES product_order (id); ALTER TABLE aservice ADD CONSTRAINT FK_5923AE08DB60186 FOREIGN KEY (task_id) REFERENCES task (id); failed : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE product DROP discr; ALTER TABLE product_order DROP PRIMARY KEY; ALTE' at line 1
