### ISSUE TITLE
[3h00m] Printable invoices

### ISSUE THREAD

**Issue by jorr-it** [Nexxus/NSK#92]

**Comment by jorr-it** [comment]
@ronalddebakker Could you please send me an invoice that I can use as inspiration for layout etc?

**Comment by ronalddebakker** [comment]
bij deze :)
[invoice-kopie.pdf](https://github.com/Nexxus/NSK/files/3285655/invoice-kopie.pdf)

**Comment by jorr-it** [comment]
Daarnaast ook een print voor intern gebruik, zoals al bestaat voor PO

**Comment by jorr-it** [comment]
<sub>Datum: Mon 22-7-2019 12:00<br />Gewerkt: 3h00m<br />Toelichting: #92<br />Dit is een automatisch bericht. Aan dit bericht kunnen geen rechten worden ontleend. Ref: 66508774</sub>

**Comment by ronalddebakker** [comment]
i can not print invoices. 
i can only print the solesorder. which is not the same...
or should there be a different issue for this?
